// lib/db/sales-tax-filings.ts
// Phase 3.11 — Sales-tax filings ledger.
//
// One row per state per filing period (month or quarter). The cron sweep
// (`regenerateUpcomingFilings` in `lib/domain/sales-tax-reports.ts`) writes
// these idempotently keyed by `(stateCode, periodStart, periodEnd)`.
//
// Server-only.

import { adminDb } from "@/lib/firebase-admin";
import { FieldValue, Timestamp } from "firebase-admin/firestore";

export type FilingStatus = "DUE_SOON" | "OVERDUE" | "FILED" | "PAID";

export interface SalesTaxFilingDoc {
  id: string;
  stateCode: string; // two-letter, uppercase
  periodStart: Timestamp; // first day of period, UTC midnight
  periodEnd: Timestamp; // last day of period, UTC midnight (inclusive)
  dueBy: Timestamp; // filing deadline
  taxableSalesCents: number;
  taxOwedCents: number;
  status: FilingStatus;
  filedAt?: Timestamp | null;
  paidAt?: Timestamp | null;
  notes?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export const salesTaxFilingsCol = () => adminDb.collection("salesTaxFilings");

function rowFromSnap(d: FirebaseFirestore.QueryDocumentSnapshot | FirebaseFirestore.DocumentSnapshot): SalesTaxFilingDoc {
  return { id: d.id, ...(d.data() as Omit<SalesTaxFilingDoc, "id">) };
}

export async function getSalesTaxFiling(id: string): Promise<SalesTaxFilingDoc | null> {
  const snap = await salesTaxFilingsCol().doc(id).get();
  return snap.exists ? rowFromSnap(snap) : null;
}

/**
 * List every filing, newest period first. Used by the admin tax report.
 * Compliance dashboard (sibling B1) also reads via this helper name.
 */
export async function listSalesTaxFilings(): Promise<SalesTaxFilingDoc[]> {
  const snap = await salesTaxFilingsCol()
    .orderBy("periodEnd", "desc")
    .limit(500)
    .get();
  return snap.docs.map(rowFromSnap);
}

/**
 * Alias kept for compliance bucket's discovery — `compliance.ts` calls
 * `listFilings` as a fallback alongside `listSalesTaxFilings`.
 */
export const listFilings = listSalesTaxFilings;

export interface UpsertFilingInput {
  stateCode: string;
  periodStart: Timestamp;
  periodEnd: Timestamp;
  dueBy: Timestamp;
  taxableSalesCents: number;
  taxOwedCents: number;
  status: FilingStatus;
  notes?: string;
}

export async function createSalesTaxFiling(
  input: UpsertFilingInput
): Promise<SalesTaxFilingDoc> {
  const now = Timestamp.now();
  const ref = salesTaxFilingsCol().doc();
  const payload = {
    stateCode: input.stateCode.toUpperCase(),
    periodStart: input.periodStart,
    periodEnd: input.periodEnd,
    dueBy: input.dueBy,
    taxableSalesCents: Math.max(0, Math.round(input.taxableSalesCents)),
    taxOwedCents: Math.max(0, Math.round(input.taxOwedCents)),
    status: input.status,
    notes: input.notes ?? "",
    filedAt: null,
    paidAt: null,
    createdAt: now,
    updatedAt: now,
  };
  await ref.set(payload);
  return { id: ref.id, ...payload } as SalesTaxFilingDoc;
}

export async function updateSalesTaxFiling(
  id: string,
  patch: Partial<Omit<SalesTaxFilingDoc, "id" | "createdAt">>
): Promise<void> {
  await salesTaxFilingsCol()
    .doc(id)
    .update({ ...patch, updatedAt: FieldValue.serverTimestamp() });
}

/**
 * Find an existing filing row for the (stateCode, periodStart, periodEnd)
 * triple. Used by `regenerateUpcomingFilings` to enforce idempotency.
 *
 * `periodEnd` matching tolerates a 24h drift to handle UTC vs local-time
 * boundary jitter — periods generated by the same helper always match
 * exactly, but admin-entered values may be a day off.
 */
export async function findExistingFiling(
  stateCode: string,
  periodStart: Timestamp,
  periodEnd: Timestamp
): Promise<SalesTaxFilingDoc | null> {
  const code = stateCode.toUpperCase();
  const snap = await salesTaxFilingsCol()
    .where("stateCode", "==", code)
    .where("periodStart", "==", periodStart)
    .limit(5)
    .get();
  if (snap.empty) return null;

  const endMs = periodEnd.toMillis();
  const DAY_MS = 24 * 60 * 60 * 1000;
  for (const d of snap.docs) {
    const r = rowFromSnap(d);
    if (Math.abs(r.periodEnd.toMillis() - endMs) <= DAY_MS) {
      return r;
    }
  }
  return null;
}

/**
 * Locate the active filing row for a given state on a given moment. Returns
 * `null` if no row covers `now`.
 */
export async function getCurrentPeriodFiling(
  stateCode: string,
  now: Date
): Promise<SalesTaxFilingDoc | null> {
  const code = stateCode.toUpperCase();
  const nowTs = Timestamp.fromDate(now);
  const snap = await salesTaxFilingsCol()
    .where("stateCode", "==", code)
    .where("periodStart", "<=", nowTs)
    .orderBy("periodStart", "desc")
    .limit(5)
    .get();
  for (const d of snap.docs) {
    const r = rowFromSnap(d);
    if (r.periodEnd.toMillis() >= now.getTime()) return r;
  }
  return null;
}

/**
 * Filings with `dueBy` within the next `lookaheadDays` and `status` still
 * outstanding (DUE_SOON or OVERDUE).
 */
export async function listUpcomingFilings(
  now: Date,
  lookaheadDays: number
): Promise<SalesTaxFilingDoc[]> {
  const nowMs = now.getTime();
  const horizonMs = nowMs + lookaheadDays * 24 * 60 * 60 * 1000;
  // Pull all outstanding and filter in-memory — cheap at studio scale and
  // dodges a composite index.
  const snap = await salesTaxFilingsCol()
    .where("status", "in", ["DUE_SOON", "OVERDUE"])
    .limit(500)
    .get();
  return snap.docs
    .map(rowFromSnap)
    .filter((r) => {
      const dueMs = r.dueBy.toMillis();
      return dueMs >= nowMs && dueMs <= horizonMs;
    })
    .sort((a, b) => a.dueBy.toMillis() - b.dueBy.toMillis());
}

/**
 * Filings whose `dueBy` is already past and whose status is still outstanding.
 */
export async function listOverdueFilings(now: Date): Promise<SalesTaxFilingDoc[]> {
  const nowMs = now.getTime();
  const snap = await salesTaxFilingsCol()
    .where("status", "in", ["DUE_SOON", "OVERDUE"])
    .limit(500)
    .get();
  return snap.docs
    .map(rowFromSnap)
    .filter((r) => r.dueBy.toMillis() < nowMs)
    .sort((a, b) => a.dueBy.toMillis() - b.dueBy.toMillis());
}

/**
 * Mark a filing as filed (paperwork submitted). Does NOT mark it paid —
 * the admin clicks a separate button once Korrin actually remits.
 */
export async function markFilingFiled(id: string): Promise<void> {
  await salesTaxFilingsCol().doc(id).update({
    status: "FILED",
    filedAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  });
}

export async function markFilingPaid(id: string, paidAt: Date): Promise<void> {
  await salesTaxFilingsCol().doc(id).update({
    status: "PAID",
    paidAt: Timestamp.fromDate(paidAt),
    updatedAt: FieldValue.serverTimestamp(),
  });
}
