// components/site-editor/styles.ts
// Shared inline-style constants for the on-page editor. Re-used by forms,
// drawer, edit bar and section toolbar so the editor chrome stays consistent.

export const editorStyles = {
  field: {
    display: "block" as const,
    marginBottom: "1rem",
  },
  fieldLabel: {
    display: "block" as const,
    fontSize: "0.65rem",
    letterSpacing: "0.18em",
    textTransform: "uppercase" as const,
    color: "var(--charcoal-muted)",
    marginBottom: "0.4rem",
  },
  input: {
    width: "100%",
    border: "0.5px solid var(--border)",
    background: "var(--white)",
    padding: "0.55rem 0.65rem",
    fontSize: "0.9rem",
    color: "var(--charcoal)",
    fontFamily: "inherit",
  } as React.CSSProperties,
  textarea: {
    width: "100%",
    border: "0.5px solid var(--border)",
    background: "var(--white)",
    padding: "0.55rem 0.65rem",
    fontSize: "0.9rem",
    color: "var(--charcoal)",
    fontFamily: "inherit",
    lineHeight: 1.6,
    resize: "vertical" as const,
  },
  select: {
    width: "100%",
    border: "0.5px solid var(--border)",
    background: "var(--white)",
    padding: "0.55rem 0.65rem",
    fontSize: "0.9rem",
    color: "var(--charcoal)",
    fontFamily: "inherit",
  } as React.CSSProperties,
  miniBtn: {
    padding: "0.25rem 0.45rem",
    fontSize: "0.7rem",
    background: "transparent",
    border: "0.5px solid var(--border)",
    color: "var(--charcoal-light)",
    cursor: "pointer",
  } as React.CSSProperties,
  addBtn: {
    width: "100%",
    border: "0.5px dashed var(--border-strong)",
    background: "transparent",
    padding: "0.45rem 0.6rem",
    fontSize: "0.78rem",
    color: "var(--charcoal-light)",
    cursor: "pointer",
    textAlign: "left" as const,
  },
  primaryBtn: {
    padding: "0.55rem 1rem",
    fontSize: "0.7rem",
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
    background: "var(--charcoal)",
    color: "var(--white)",
    border: "none",
    cursor: "pointer",
  } as React.CSSProperties,
  publishBtn: {
    padding: "0.55rem 1rem",
    fontSize: "0.7rem",
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
    background: "var(--olive)",
    color: "var(--white)",
    border: "none",
    cursor: "pointer",
  } as React.CSSProperties,
  secondaryBtn: {
    padding: "0.55rem 1rem",
    fontSize: "0.7rem",
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
    background: "transparent",
    color: "var(--charcoal-light)",
    border: "0.5px solid var(--border)",
    cursor: "pointer",
  } as React.CSSProperties,
} as const;

export const SECTION_LABEL: Record<string, string> = {
  HERO: "Hero",
  PHOTO_GRID: "Photo grid",
  RICH_TEXT: "Rich text",
  CTA_BANNER: "CTA banner",
  PROCESS_STEPS: "Process steps",
  PACKAGE_CARDS: "Package cards",
  TESTIMONIAL: "Testimonial",
  SLIDESHOW: "Slideshow",
  STATS: "Stats",
  BOOKING_FORM: "Booking form",
};

export const SECTION_DESCRIPTION: Record<string, string> = {
  HERO: "Full-bleed banner with a headline and background image.",
  PHOTO_GRID: "A tidy grid of photos with an optional heading.",
  SLIDESHOW: "Auto-cycling full-width photo slideshow.",
  STATS: "A row of big numbers (sessions, years, etc.).",
  RICH_TEXT: "A block of formatted prose.",
  CTA_BANNER: "A call-to-action band with buttons.",
  PROCESS_STEPS: "Numbered steps describing your process.",
  PACKAGE_CARDS: "Pricing and package cards with features.",
  TESTIMONIAL: "A featured client quote.",
  BOOKING_FORM: "Embeds the booking inquiry form.",
};
